# Generated by Django 5.2.5 on 2025-11-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(blank=True, choices=[('Business', 'Business'), ('Sports', 'Sports'), ('Lifestyle', 'Lifestyle'), ('Tech', 'Tech')], max_length=255, null=True),
        ),
    ]
